name: CI/CD Pipeline with TLS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: srirammanyam/wisecow:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          wait: 120s

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Verify cluster status
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/kind/deploy.yaml
          echo "Skipping waiting for ingress-nginx controller readiness (Kind CI limitation)"

      - name: Deploy Cert-Manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml

      - name: Wait for Cert-Manager to be ready
        run: |
          kubectl rollout status deployment cert-manager -n cert-manager --timeout=600s
          kubectl rollout status deployment cert-manager-webhook -n cert-manager --timeout=600s
          kubectl rollout status deployment cert-manager-cainjector -n cert-manager --timeout=600s

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f cluster-issuer.yaml
          kubectl apply -f ingress.yaml

      - name: Verify app deployment
        run: |
          kubectl rollout status deployment wisecow-deployment -n default --timeout=300s
          kubectl get pods -o wide

